# Generated by Django 5.0.3 on 2024-03-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_numer_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='numer_rating',
            new_name='number_rating',
        ),
    ]
